name: Task 3

on:
  push:
    paths:
      - '03_qt_git/**'
  pull_request:
    paths:
      - '03_qt_git/**'
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug
  PROJECT_DIR: ${{github.workspace}}/03_qt_git/

jobs:
  build-ubuntu:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.14.0
      with:
        version: 5.15.2
        set-env: true
    - name: Configure CMake
      run: cmake -B ${{env.PROJECT_DIR}}/build -S ${{env.PROJECT_DIR}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Build
      run: cmake --build ${{env.PROJECT_DIR}}/build --config ${{env.BUILD_TYPE}}
      
  build-windows:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v2
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.14.0
      with:
        version: 5.15.2
        set-env: true
    - name: Configure CMake
      run: cmake -B ${{env.PROJECT_DIR}}/build -S ${{env.PROJECT_DIR}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Build
      run: cmake --build ${{env.PROJECT_DIR}}/build --config ${{env.BUILD_TYPE}}
